### ISSUE TITLE
[idea] Rewrite as a composite action?

### ISSUE THREAD

**Issue by webknjaz** [mtkennerly/dunamai-action#2]
I understand that this action was started back when composite actions weren't as usable. Now that they are, it seems like a good idea to get rid of NodeJS: it'd mean less code and no need for a transpiler... Plus, you could use Python for the main logic if that suits your needs. Here's an action example that uses Python in separate modules: https://github.com/re-actors/alls-green. And here's an example that embeds bits of Python in YAML: https://github.com/ansible-community/ansible-test-gh-action — it's not as elegant, though, I'm planning to fix that.

**Comment by mtkennerly** [comment]
This sounds reasonable to me :) I would miss having access to `@actions/core`, but the overall complexity trade-off should be for the better, since this is such a simple action.

**Comment by mtkennerly** [comment]
Done and released as v1.3.0. Thanks for the suggestion!
